version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - aws --version
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      - eval $(aws ecr get-login --region us-east-1 --no-include-email | sed 's|https://||')

  pre_build:
    commands:
      - REPOSITORY_URI=public.ecr.aws/a0t2b5b9/terajus-staging
      - IMAGE_TAG=1.0

  build:
    commands:
      - echo ===================
      - echo $REPOSITORY_URI
      - echo ==================
#      - composer install
#      - php artisan key:generate
#      - php artisan cache:clear
#      - php artisan config:clear
#      - php artisan migrate --force
#      - cp .env.example .env
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
#
#enviroments:
#  type: linux-container
