version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/development:/etc/nginx/conf.d/
        networks:
            - laravel

    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/postgres/dbdata:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        networks:
            - laravel

    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: always
        ports:
            - '${MONGODB_PORT:-27017}:27017'
        volumes:
            - ./mongodb-data:/data/db
        networks:
            - laravel
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGODB_DATABASE}'
        command: mongod --auth

    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
