version: "3.7"

services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        depends_on:
            - mysql
        networks:
            - laravel

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
